name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: stable
    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.4.0
      with:
        install-go: false
